// 
// Decompiled by Procyon v0.5.30
// 

package com.google.android.gms.internal;

import java.util.List;
import com.google.android.gms.ads.internal.zzu;
import java.util.concurrent.Callable;
import android.content.Context;
import java.util.concurrent.TimeUnit;

@zziy
public final class zzdi
{
    public static final zzde<String> zzban;
    public static final zzde<String> zzbao;
    public static final zzde<Boolean> zzbap;
    public static final zzde<String> zzbaq;
    public static final zzde<Boolean> zzbar;
    public static final zzde<String> zzbas;
    public static final zzde<Boolean> zzbat;
    public static final zzde<Boolean> zzbau;
    public static final zzde<String> zzbav;
    public static final zzde<Boolean> zzbaw;
    public static final zzde<String> zzbax;
    public static final zzde<String> zzbay;
    public static final zzde<String> zzbaz;
    public static final zzde<Boolean> zzbba;
    public static final zzde<Integer> zzbbb;
    public static final zzde<String> zzbbc;
    public static final zzde<String> zzbbd;
    public static final zzde<Integer> zzbbe;
    public static final zzde<Integer> zzbbf;
    public static final zzde<Integer> zzbbg;
    public static final zzde<Integer> zzbbh;
    public static final zzde<Long> zzbbi;
    public static final zzde<Long> zzbbj;
    public static final zzde<Integer> zzbbk;
    public static final zzde<Boolean> zzbbl;
    public static final zzde<String> zzbbm;
    public static final zzde<Long> zzbbn;
    public static final zzde<Boolean> zzbbo;
    public static final zzde<Boolean> zzbbp;
    public static final zzde<Boolean> zzbbq;
    public static final zzde<String> zzbbr;
    public static final zzde<Boolean> zzbbs;
    public static final zzde<String> zzbbt;
    public static final zzde<Boolean> zzbbu;
    public static final zzde<Boolean> zzbbv;
    public static final zzde<Boolean> zzbbw;
    public static final zzde<String> zzbbx;
    public static final zzde<String> zzbby;
    public static final zzde<String> zzbbz;
    public static final zzde<Boolean> zzbca;
    public static final zzde<String> zzbcb;
    public static final zzde<Boolean> zzbcc;
    public static final zzde<Boolean> zzbcd;
    public static final zzde<Integer> zzbce;
    public static final zzde<Integer> zzbcf;
    public static final zzde<Integer> zzbcg;
    public static final zzde<Integer> zzbch;
    public static final zzde<Integer> zzbci;
    public static final zzde<Boolean> zzbcj;
    public static final zzde<Boolean> zzbck;
    public static final zzde<Long> zzbcl;
    public static final zzde<String> zzbcm;
    public static final zzde<String> zzbcn;
    public static final zzde<Boolean> zzbco;
    public static final zzde<Boolean> zzbcp;
    public static final zzde<Boolean> zzbcq;
    public static final zzde<String> zzbcr;
    public static final zzde<Boolean> zzbcs;
    public static final zzde<Boolean> zzbct;
    public static final zzde<Integer> zzbcu;
    public static final zzde<Boolean> zzbcv;
    public static final zzde<String> zzbcw;
    public static final zzde<Boolean> zzbcx;
    public static final zzde<String> zzbcy;
    public static final zzde<String> zzbcz;
    public static final zzde<Long> zzbda;
    public static final zzde<Boolean> zzbdb;
    public static final zzde<Long> zzbdc;
    public static final zzde<Long> zzbdd;
    public static final zzde<Boolean> zzbde;
    public static final zzde<String> zzbdf;
    public static final zzde<Boolean> zzbdg;
    public static final zzde<Long> zzbdh;
    public static final zzde<Boolean> zzbdi;
    public static final zzde<Boolean> zzbdj;
    public static final zzde<String> zzbdk;
    public static final zzde<String> zzbdl;
    public static final zzde<Integer> zzbdm;
    public static final zzde<Integer> zzbdn;
    public static final zzde<Integer> zzbdo;
    public static final zzde<String> zzbdp;
    public static final zzde<String> zzbdq;
    public static final zzde<String> zzbdr;
    public static final zzde<String> zzbds;
    public static final zzde<Boolean> zzbdt;
    public static final zzde<Boolean> zzbdu;
    public static final zzde<String> zzbdv;
    public static final zzde<Boolean> zzbdw;
    public static final zzde<Long> zzbdx;
    public static final zzde<Boolean> zzbdy;
    public static final zzde<Boolean> zzbdz;
    public static final zzde<Boolean> zzbea;
    public static final zzde<Boolean> zzbeb;
    public static final zzde<Boolean> zzbec;
    public static final zzde<Boolean> zzbed;
    public static final zzde<Boolean> zzbee;
    public static final zzde<Boolean> zzbef;
    public static final zzde<String> zzbeg;
    public static final zzde<Long> zzbeh;
    public static final zzde<Boolean> zzbei;
    public static final zzde<Boolean> zzbej;
    public static final zzde<Long> zzbek;
    public static final zzde<Long> zzbel;
    public static final zzde<Boolean> zzbem;
    public static final zzde<Long> zzben;
    public static final zzde<String> zzbeo;
    public static final zzde<Boolean> zzbep;
    public static final zzde<String> zzbeq;
    public static final zzde<Boolean> zzber;
    public static final zzde<Boolean> zzbes;
    public static final zzde<String> zzbet;
    public static final zzde<Boolean> zzbeu;
    public static final zzde<String> zzbev;
    public static final zzde<Boolean> zzbew;
    public static final zzde<Boolean> zzbex;
    public static final zzde<String> zzbey;
    public static final zzde<Boolean> zzbez;
    public static final zzde<String> zzbfa;
    public static final zzde<Boolean> zzbfb;
    public static final zzde<String> zzbfc;
    public static zzde<Boolean> zzbfd;
    public static zzde<String> zzbfe;
    public static final zzde<String> zzbff;
    public static final zzde<Boolean> zzbfg;
    public static final zzde<Boolean> zzbfh;
    public static final zzde<String> zzbfi;
    public static final zzde<Boolean> zzbfj;
    public static final zzde<Boolean> zzbfk;
    public static final zzde<Boolean> zzbfl;
    public static final zzde<Boolean> zzbfm;
    public static final zzde<Boolean> zzbfn;
    public static final zzde<Boolean> zzbfo;
    public static final zzde<String> zzbfp;
    public static final zzde<String> zzbfq;
    public static final zzde<String> zzbfr;
    public static final zzde<Long> zzbfs;
    public static final zzde<Boolean> zzbft;
    public static final zzde<Boolean> zzbfu;
    public static final zzde<String> zzbfv;
    public static final zzde<String> zzbfw;
    public static final zzde<Boolean> zzbfx;
    public static final zzde<String> zzbfy;
    public static final zzde<Boolean> zzbfz;
    public static final zzde<Boolean> zzbga;
    public static final zzde<Integer> zzbgb;
    public static final zzde<String> zzbgc;
    public static final zzde<String> zzbgd;
    public static final zzde<Boolean> zzbge;
    public static final zzde<Boolean> zzbgf;
    public static final zzde<Boolean> zzbgg;
    public static final zzde<Long> zzbgh;
    public static final zzde<Integer> zzbgi;
    public static final zzde<Integer> zzbgj;
    public static final zzde<Boolean> zzbgk;
    public static final zzde<String> zzbgl;
    public static final zzde<Long> zzbgm;
    public static final zzde<String> zzbgn;
    public static final zzde<Long> zzbgo;
    public static final zzde<String> zzbgp;
    public static final zzde<Boolean> zzbgq;
    public static final zzde<String> zzbgr;
    public static final zzde<Long> zzbgs;
    public static final zzde<String> zzbgt;
    public static final zzde<String> zzbgu;
    public static final zzde<String> zzbgv;
    public static final zzde<String> zzbgw;
    public static final zzde<String> zzbgx;
    public static final zzde<String> zzbgy;
    public static final zzde<String> zzbgz;
    public static final zzde<Long> zzbha;
    public static final zzde<Boolean> zzbhb;
    public static final zzde<Boolean> zzbhc;
    public static final zzde<Long> zzbhd;
    public static final zzde<String> zzbhe;
    public static final zzde<Long> zzbhf;
    public static final zzde<Boolean> zzbhg;
    public static final zzde<Boolean> zzbhh;
    public static final zzde<Integer> zzbhi;
    public static final zzde<Long> zzbhj;
    public static final zzde<Boolean> zzbhk;
    public static final zzde<Boolean> zzbhl;
    public static final zzde<Boolean> zzbhm;
    public static final zzde<Long> zzbhn;
    public static final zzde<Boolean> zzbho;
    public static final zzde<Boolean> zzbhp;
    public static final zzde<Boolean> zzbhq;
    public static final zzde<String> zzbhr;
    public static final zzde<String> zzbhs;
    public static final zzde<String> zzbht;
    public static final zzde<String> zzbhu;
    public static final zzde<Integer> zzbhv;
    public static final zzde<Integer> zzbhw;
    public static final zzde<Boolean> zzbhx;
    
    static {
        zzban = zzde.zza(0, "gads:sdk_core_experiment_id");
        zzbao = zzde.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        zzbap = zzde.zza(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
        zzbaq = zzde.zza(0, "gads:request_builder:singleton_webview_experiment_id");
        zzbar = zzde.zza(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
        zzbas = zzde.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
        zzbat = zzde.zza(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
        zzbau = zzde.zza(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
        zzbav = zzde.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
        zzbaw = zzde.zza(0, "gads:block_autoclicks", Boolean.valueOf(false));
        zzbax = zzde.zza(0, "gads:block_autoclicks_experiment_id");
        zzbay = zzde.zzb(0, "gads:prefetch:experiment_id");
        zzbaz = zzde.zza(0, "gads:spam_app_context:experiment_id");
        zzbba = zzde.zza(1, "gads:spam_app_context:enabled", Boolean.valueOf(false));
        zzbbb = zzde.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
        zzbbc = zzde.zza(1, "gads:video_exo_player:version", "1");
        zzbbd = zzde.zza(0, "gads:video_stream_cache:experiment_id");
        zzbbe = zzde.zza(1, "gads:video_stream_cache:limit_count", 5);
        zzbbf = zzde.zza(1, "gads:video_stream_cache:limit_space", 8388608);
        zzbbg = zzde.zza(1, "gads:video_stream_exo_allocator:segment_size", 65536);
        zzbbh = zzde.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
        zzbbi = zzde.zza(1, "gads:video_stream_cache:limit_time_sec", 300L);
        zzbbj = zzde.zza(1, "gads:video_stream_cache:notify_interval_millis", 1000L);
        zzbbk = zzde.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
        zzbbl = zzde.zza(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
        zzbbm = zzde.zza(1, "gads:video:metric_frame_hash_times", "");
        zzbbn = zzde.zza(1, "gads:video:metric_frame_hash_time_leniency", 500L);
        zzbbo = zzde.zza(1, "gads:video:force_watermark", Boolean.valueOf(false));
        zzbbp = zzde.zza(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
        zzbbq = zzde.zza(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
        zzbbr = zzde.zzb(0, "gads:spam_ad_id_decorator:experiment_id");
        zzbbs = zzde.zza(0, "gads:spam_ad_id_decorator:enabled", Boolean.valueOf(false));
        zzbbt = zzde.zzb(0, "gads:looper_for_gms_client:experiment_id");
        zzbbu = zzde.zza(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
        zzbbv = zzde.zza(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
        zzbbw = zzde.zza(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
        zzbbx = zzde.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        zzbby = zzde.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        zzbbz = zzde.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        zzbca = zzde.zza(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
        zzbcb = zzde.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        zzbcc = zzde.zza(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
        zzbcd = zzde.zza(0, "gads:enable_content_fetching", Boolean.valueOf(true));
        zzbce = zzde.zza(0, "gads:content_length_weight", 1);
        zzbcf = zzde.zza(0, "gads:content_age_weight", 1);
        zzbcg = zzde.zza(0, "gads:min_content_len", 11);
        zzbch = zzde.zza(0, "gads:fingerprint_number", 10);
        zzbci = zzde.zza(0, "gads:sleep_sec", 10);
        zzbcj = zzde.zza(0, "gad:app_index_enabled", Boolean.valueOf(true));
        zzbck = zzde.zza(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
        zzbcl = zzde.zza(0, "gads:app_index:timeout_ms", 1000L);
        zzbcm = zzde.zza(0, "gads:app_index:experiment_id");
        zzbcn = zzde.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
        zzbco = zzde.zza(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
        zzbcp = zzde.zza(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
        zzbcq = zzde.zza(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
        zzbcr = zzde.zza(0, "gads:interstitial_follow_url:experiment_id");
        zzbcs = zzde.zza(0, "gads:analytics_enabled", Boolean.valueOf(true));
        zzbct = zzde.zza(0, "gads:ad_key_enabled", Boolean.valueOf(false));
        zzbcu = zzde.zza(0, "gads:webview_cache_version", 0);
        zzbcv = zzde.zza(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
        zzbcw = zzde.zza(1, "gads:webview_recycle:experiment_id");
        zzbcx = zzde.zza(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
        zzbcy = zzde.zzb(0, "gads:pan:experiment_id");
        zzbcz = zzde.zza(1, "gads:rewarded:experiment_id");
        zzbda = zzde.zza(1, "gads:rewarded:adapter_timeout_ms", 20000L);
        zzbdb = zzde.zza(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
        zzbdc = zzde.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
        zzbdd = zzde.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5L));
        zzbde = zzde.zza(0, "gads:ad_manager_creator:enabled", Boolean.valueOf(true));
        zzbdf = zzde.zza(1, "gads:ad_manager_enforce_arp_invariant:experiment_id");
        zzbdg = zzde.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
        zzbdh = zzde.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
        zzbdi = zzde.zza(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
        zzbdj = zzde.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
        zzbdk = zzde.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        zzbdl = zzde.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        zzbdm = zzde.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
        zzbdn = zzde.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        zzbdo = zzde.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        zzbdp = zzde.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        zzbdq = zzde.zza(1, "gads:spherical_video:vertex_shader", "");
        zzbdr = zzde.zza(1, "gads:spherical_video:fragment_shader", "");
        zzbds = zzde.zza(1, "gads:spherical_video:experiment_id");
        zzbdt = zzde.zza(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
        zzbdu = zzde.zza(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
        zzbdv = zzde.zza(1, "gads:include_local_global_rectangles:experiment_id");
        zzbdw = zzde.zza(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
        zzbdx = zzde.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
        zzbdy = zzde.zza(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
        zzbdz = zzde.zza(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
        zzbea = zzde.zza(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
        zzbeb = zzde.zza(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
        zzbec = zzde.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
        zzbed = zzde.zza(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
        zzbee = zzde.zza(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
        zzbef = zzde.zza(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
        zzbeg = zzde.zza(0, "gads:gmsg:video_meta:experiment_id");
        zzbeh = zzde.zza(0, "gads:network:cache_prediction_duration_s", 300L);
        zzbei = zzde.zza(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
        zzbej = zzde.zza(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
        zzbek = zzde.zza(0, "gads:ad_loader:timeout_ms", 60000L);
        zzbel = zzde.zza(0, "gads:rendering:timeout_ms", 60000L);
        zzbem = zzde.zza(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
        zzben = zzde.zza(1, "gads:gestures:task_timeout", 2000L);
        zzbeo = zzde.zza(1, "gads:gestures:encrypt_size_limit:experiment_id");
        zzbep = zzde.zza(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(false));
        zzbeq = zzde.zza(1, "gads:gestures:appid:experiment_id");
        zzber = zzde.zza(1, "gads:gestures:appid:enabled", Boolean.valueOf(false));
        zzbes = zzde.zza(0, "gads:gestures:v6:enabled", Boolean.valueOf(false));
        zzbet = zzde.zza(1, "gads:gestures:usb_query:experiment_id");
        zzbeu = zzde.zza(1, "gads:gestures:usb_query:enabled", Boolean.valueOf(false));
        zzbev = zzde.zza(1, "gads:gestures:usb_click:experiment_id");
        zzbew = zzde.zza(1, "gads:gestures:usb_click:enabled", Boolean.valueOf(false));
        zzbex = zzde.zza(1, "gads:gestures:touchinfo:enabled", Boolean.valueOf(false));
        zzbey = zzde.zza(1, "gads:gestures:touchinfo:experiment_id");
        zzbez = zzde.zza(1, "gads:gestures:clock_query:enabled", Boolean.valueOf(false));
        zzbfa = zzde.zza(1, "gads:gestures:clock_query:experiment_id");
        zzbfb = zzde.zza(1, "gads:gestures:clock_click:enabled", Boolean.valueOf(false));
        zzbfc = zzde.zza(1, "gads:gestures:clock_click:experiment_id");
        zzdi.zzbfd = zzde.zza(1, "gads:gestures:btl_click:enabled", Boolean.valueOf(false));
        zzdi.zzbfe = zzde.zza(1, "gads:gestures:btl_click:experiment_id");
        zzbff = zzde.zza(1, "gads:gestures:click_stk:experiment_id");
        zzbfg = zzde.zza(1, "gads:gestures:click_stk:enabled", Boolean.valueOf(true));
        zzbfh = zzde.zza(0, "gass:client:enabled", Boolean.valueOf(true));
        zzbfi = zzde.zza(0, "gass:client:experiment_id");
        zzbfj = zzde.zza(0, "gass:enabled", Boolean.valueOf(true));
        zzbfk = zzde.zza(0, "gass:enable_int_signal", Boolean.valueOf(true));
        zzbfl = zzde.zza(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
        zzbfm = zzde.zza(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
        zzbfn = zzde.zza(0, "gads:support_screen_shot", Boolean.valueOf(true));
        zzbfo = zzde.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
        zzbfp = zzde.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
        zzbfq = zzde.zza(1, "gads:sdk_core_constants:experiment_id");
        zzbfr = zzde.zza(1, "gads:sdk_core_constants:caps", "");
        zzbfs = zzde.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12L));
        zzbft = zzde.zza(0, "gads:js_flags:mf", Boolean.valueOf(false));
        zzbfu = zzde.zza(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
        zzbfv = zzde.zza(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        zzbfw = zzde.zza(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
        zzbfx = zzde.zza(1, "gads:singleton_webview_native", Boolean.valueOf(false));
        zzbfy = zzde.zza(1, "gads:singleton_webview_native:experiment_id");
        zzbfz = zzde.zza(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
        zzbga = zzde.zza(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
        zzbgb = zzde.zza(1, "gads:native_video_load_timeout", 10);
        zzbgc = zzde.zza(1, "gads:native_video_load_timeout:experiment_id");
        zzbgd = zzde.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
        zzbge = zzde.zza(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
        zzbgf = zzde.zza(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
        zzbgg = zzde.zza(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
        zzbgh = zzde.zza(0, "gads:method_tracing:duration_ms", 30000L);
        zzbgi = zzde.zza(0, "gads:method_tracing:count", 5);
        zzbgj = zzde.zza(0, "gads:method_tracing:filesize", 134217728);
        zzbgk = zzde.zza(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
        zzbgl = zzde.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
        zzbgm = zzde.zza(1, "gads:auto_location_timeout", 2000L);
        zzbgn = zzde.zzb(1, "gads:auto_location_timeout:experiment_id");
        zzbgo = zzde.zza(1, "gads:auto_location_interval", -1L);
        zzbgp = zzde.zzb(1, "gads:auto_location_interval:experiment_id");
        zzbgq = zzde.zza(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
        zzbgr = zzde.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
        zzbgs = zzde.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
        zzbgt = zzde.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
        zzbgu = zzde.zza(0, "gads:afs:csa:experiment_id");
        zzbgv = zzde.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
        zzbgw = zzde.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
        zzbgx = zzde.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
        zzbgy = zzde.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
        zzbgz = zzde.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
        zzbha = zzde.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
        zzbhb = zzde.zza(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
        zzbhc = zzde.zza(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
        zzbhd = zzde.zza(1, "gads:parental_controls:timeout", 2000L);
        zzbhe = zzde.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
        zzbhf = zzde.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
        zzbhg = zzde.zza(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
        zzbhh = zzde.zza(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
        zzbhi = zzde.zza(1, "gads:cache:max_concurrent_downloads", 10);
        zzbhj = zzde.zza(1, "gads:cache:javascript_timeout_millis", 5000L);
        zzbhk = zzde.zza(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
        zzbhl = zzde.zza(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
        zzbhm = zzde.zza(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
        zzbhn = zzde.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30L));
        zzbho = zzde.zza(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
        zzbhp = zzde.zza(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
        zzbhq = zzde.zza(1, "gads:drx_debug:enabled", Boolean.valueOf(false));
        zzbhr = zzde.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        zzbhs = zzde.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        zzbht = zzde.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        zzbhu = zzde.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        zzbhv = zzde.zza(1, "gads:drx_debug:timeout_ms", 5000);
        zzbhw = zzde.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
        zzbhx = zzde.zza(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    }
    
    public static void initialize(final Context context) {
        zzle.zzb((Callable<Object>)new Callable<Void>() {
            public Void zzdb() {
                zzu.zzgl().initialize(context);
                return null;
            }
        });
    }
    
    public static List<String> zzkr() {
        return zzu.zzgk().zzkr();
    }
    
    public static List<String> zzks() {
        return zzu.zzgk().zzks();
    }
}
